# Generated by Django 4.1.2 on 2022-11-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emprestimo_aprovado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='imagem',
        ),
        migrations.AddField(
            model_name='livro',
            name='base64',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(),
        ),
    ]
