# Generated by Django 4.1.2 on 2022-11-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_livro_imagem_livro_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='user',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='base64',
            field=models.TextField(default=None),
        ),
    ]
