# Generated by Django 4.1.2 on 2022-11-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emprestimo_user_alter_livro_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='user',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
