# Generated by Django 4.1.2 on 2022-11-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_emprestimo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='user',
        ),
    ]
