# Generated by Django 4.1.2 on 2022-10-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_ano_livro_autor_alter_livro_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('idLivros', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
