# Generated by Django 4.1.2 on 2022-10-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_emprestimo_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(default=None, upload_to='imgs'),
        ),
    ]
