# Generated by Django 4.1.2 on 2022-10-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_livro_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='idLivros',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='idLivro',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='username',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
