# Generated by Django 4.1.2 on 2022-10-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_remove_emprestimo_idlivros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='idLivro',
            field=models.IntegerField(unique=True),
        ),
    ]
